[package]
name = "languages"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[features]
test-support = [
    "load-grammars"
]
load-grammars = [
    "grammars/load-grammars",
    "tree-sitter",
    "tree-sitter-gitcommit",
]

[dependencies]
gpui.workspace = true
grammars.workspace = true
language.workspace = true
settings.workspace = true
smol.workspace = true
tree-sitter = { workspace = true, optional = true }
tree-sitter-gitcommit = { workspace = true, optional = true }
util.workspace = true

[dev-dependencies]
tree-sitter.workspace = true
